### ISSUE TITLE
New version not available

### ISSUE THREAD

**Issue by AsciiWolf** [flathub/org.gnome.Mahjongg#3]
It looks like that the latest 3.34.0 version from commit de976e818e341fb7aff95709c1661443c93b5e9b is not available [on Flathub](https://flathub.org/apps/details/org.gnome.Mahjongg) although there were no issues during its build. Not sure what happened.

**Comment by AsciiWolf** [comment]
[GNOME Mines](https://github.com/flathub/org.gnome.Mines) and [Tali](https://github.com/flathub/org.gnome.Tali) seem to have the same issue.

**Comment by bilelmoussaoui** [comment]
I triggered a new build for the three games but I looked at the metainfo of Mahjongg and it didn't got a version bump https://gitlab.gnome.org/GNOME/gnome-mahjongg/blob/master/data/org.gnome.Mahjongg.appdata.xml.in#L30 :(

**Comment by bilelmoussaoui** [comment]
Seems to be metainfo related; closing

**Comment by AsciiWolf** [comment]
Could you report the issue upstream? :-) I would do it, but I am quite busy lately. :-/

**Comment by bilelmoussaoui** [comment]
That's an issue in a lot of GNOME apps and would require rather an email to desktop-devel-list & ask the developers to update the metainfo before each new stable release.
Will send an email soon
